version: '3'
services:
  nginx:
    image: tensorflow-api-nginx    
    container_name: tensorflow-api-nginx
    build: 
      context: ./nginx
    tty: true      
  express:
    image: tensorflow-api-express    
    container_name: tensorflow-api-express
    build:
      context: ./express
    tty: true    